version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template .docker/app/.env_tmpl:.env -wait tcp://db:3306 -timeout 40s ./entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis

    networks:
      - app-network

  nginx:
    build: .docker/nginx
    container_name: nginx
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.conf_tmpl:/etc/nginx/conf.d/nginx.conf /docker-entrypoint.sh
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    tty: true
    environment:
      - APP_NAME=app
      - APP_PORT=9000
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
